version: "3"
services:
  spine1:
    privileged: true
    image: frr
    build:
      context: .
    expose:
      - 179
    tty: true
    networks:
      spine1leaf1:
        ipv4_address: 10.1.1.2
      spine1leaf2:
        ipv4_address: 10.1.2.2
      spine1edge1:
        ipv4_address: 10.1.3.2
    volumes:
      - ./spine1/:/etc/frr/
  leaf1:
    privileged: true
    image: frr
    build:
      context: .
    expose:
      - 179
    tty: true
    networks:
      spine1leaf1:
        ipv4_address: 10.1.1.3
    volumes:
      - ./leaf1/:/etc/frr/
  leaf2:
    privileged: true
    image: frr
    build:
      context: .
    expose:
      - 179
    tty: true
    networks:
      spine1leaf2:
        ipv4_address: 10.1.2.3
    volumes:
      - ./leaf2/:/etc/frr/
  edge1:
    privileged: true
    image: frr
    build:
      context: .
    expose:
      - 179
    tty: true
    networks:
      spine1edge1:
        ipv4_address: 10.1.3.3
      border1edge1:
        ipv4_address: 172.18.0.2
    volumes:
      - ./edge1/:/etc/frr/
  border1:
    image: frr
    build:
      context: .
    expose:
      - 179
    tty: true
    networks:
      border1edge1:
        ipv4_address: 172.18.0.3
    volumes:
      - ./border1/:/etc/frr/
networks:
  spine1leaf1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/29
  spine1leaf2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.2.0/29
  spine1edge1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.3.0/29
  border1edge1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/29
